services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: betabae
        ports:
            - '3306:3306'
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        command: sh -c "mkdir -p /var/log/redis && chown redis:redis /var/log/redis && redis-server /usr/local/etc/redis/redis.conf"
        ports:
            - '6379:6379'
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
            - redis_data:/data
            - redis_logs:/var/log/redis
        networks:
            - app-network

    minio:
        image: minio/minio:latest
        container_name: minio
        command: server /data --console-address ":9001"
        ports:
            - '9000:9000' # S3 API
            - '9001:9001' # Console UI
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        volumes:
            - minio_data:/data
        networks:
            - app-network

    minio-init:
        image: minio/mc
        container_name: minio-init
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
                until mc alias set local http://minio:9000 minioadmin minioadmin; do sleep 1; done;
                mc mb -p local/betabae || true;
                mc anonymous set download local/betabae
            "
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    redis_data:
    redis_logs:
    minio_data:
